# Generated by Django 3.0.2 on 2020-01-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='servers',
        ),
        migrations.RemoveField(
            model_name='server',
            name='created',
        ),
        migrations.RemoveField(
            model_name='server',
            name='fqdn',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='server',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='server',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='server',
            name='script',
        ),
        migrations.RemoveField(
            model_name='server',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='server',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='team',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='team',
            name='servers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated',
        ),
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ManyToManyField(blank=True, related_name='_project_server_+', to='manager.Server'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='_project_team_+', to='manager.Team'),
        ),
        migrations.AddField(
            model_name='server',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manager.Team', verbose_name='Associated Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='_team_project_+', to='manager.Project', verbose_name='Associated Projects'),
        ),
        migrations.AddField(
            model_name='team',
            name='server',
            field=models.ManyToManyField(blank=True, related_name='_team_server_+', to='manager.Server', verbose_name='Associated Servers'),
        ),
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manager.Project', verbose_name='Associated Project'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
