# Generated by Django 3.0.2 on 2020-01-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200115_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='server',
            name='slug',
        ),
    ]
