# Generated by Django 3.0.2 on 2020-01-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(to='dashboard.Team', verbose_name='Associated Teams'),
        ),
    ]
