# Generated by Django 3.0.2 on 2020-01-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project')),
                ('project_servers', models.ManyToManyField(blank=True, related_name='servers_related_to_project', to='dashboard.Server', verbose_name='Associated Supported Servers')),
                ('project_team_servers', models.ManyToManyField(blank=True, related_name='projects_team_servers', to='dashboard.Team', verbose_name='Teams that Support the Project')),
            ],
        ),
    ]
