# Generated by Django 3.0.2 on 2020-01-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ManyToManyField(to='dashboard.Server', verbose_name='Associated Servers'),
        ),
    ]
