# Generated by Django 3.0.2 on 2020-01-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_projectmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='project_servers',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='project_team_servers',
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='server',
            field=models.ManyToManyField(blank=True, related_name='project_server', to='dashboard.Server', verbose_name='Associated Supported Servers'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team_server', to='dashboard.Team', verbose_name='Teams that Support the Project'),
        ),
    ]
