# Generated by Django 3.0.2 on 2020-01-14 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_project_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_project', to='dashboard.Project', verbose_name='Associated Project'),
        ),
        migrations.AddField(
            model_name='server',
            name='team',
            field=models.ManyToManyField(to='dashboard.Team', verbose_name='Associated Teams'),
        ),
        migrations.AlterField(
            model_name='project',
            name='server',
            field=models.ManyToManyField(related_name='project_server', to='dashboard.Server', verbose_name='Associated Servers'),
        ),
    ]
