# Generated by Django 3.0.2 on 2020-01-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200114_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmanager',
            options={'verbose_name': 'Project Manager', 'verbose_name_plural': 'Project Manager'},
        ),
    ]
