# Generated by Django 3.0.2 on 2020-01-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200114_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='server',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.RemoveField(
            model_name='server',
            name='project',
        ),
        migrations.RemoveField(
            model_name='server',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.RemoveField(
            model_name='team',
            name='server',
        ),
    ]
