# Generated by Django 3.0.2 on 2020-01-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash2.Project')),
                ('project_servers', models.ManyToManyField(blank=True, related_name='servers_related_to_project', to='dash2.Server', verbose_name='Associated Supported Servers')),
                ('project_team_servers', models.ManyToManyField(blank=True, related_name='projects_team_servers', to='dash2.Team', verbose_name='Teams that Support the Project')),
            ],
        ),
    ]
