# Generated by Django 3.0.2 on 2020-01-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash2', '0002_auto_20200114_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
