# Generated by Django 3.0.2 on 2020-01-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash2', '0003_auto_20200114_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanager',
            old_name='project_servers',
            new_name='server',
        ),
        migrations.RenameField(
            model_name='projectmanager',
            old_name='project_team_servers',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='project_name',
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='name',
            field=models.ForeignKey(default='Hello', on_delete=django.db.models.deletion.CASCADE, to='dash2.Project'),
            preserve_default=False,
        ),
    ]
